### ISSUE TITLE
track more forms

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/mapping-tracker#1]
- africa_heathfacilities_v2
- africa_poi
- africa_schools
- africa_waterpoints
- building_placeholders
- buildings
- Guinee_Sondage_Communautaire_V1-3-5
- Liberia_Community_Survey_Mar2016_MF_v1
- Sierra_Leone_Community_Survey_V0-0-1

**Comment by danbjoseph** [comment]
need a loading gif or something on the main map. but this is done.
